name: "Generate Polyglot"

on:
  push:
    branches:
      - master
    paths:
      - "resume_devsecops.tex"
      - "resume_cybersec.tex"
      - "experience/**"
      - "icons/**"
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install build dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y autoconf clang gettext liblocale-msgfmt-perl texlive-full

            - name: Set git config
              run: |
                git config --global user.name "GitHub Actions [bot]"
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

            - name: Build Polyglot PDFs
              run: |
                make -f Makefile_DevSecOps
                make -f Makefile_CyberSec

            - name: Set release tag
              id: tag
              run: echo "TAG=$(date +'%Y-%m-%d')_$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            
            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "CJ_May_Resume_DevSecOps.pdf,CJ_May_Resume_CyberSec.pdf"
                token: ${{ secrets.GITHUB_TOKEN }}
                tag: ${{ steps.tag.outputs.TAG }}
                name: "CJ May Resume"
                body: "Automatically generated PDFs from LaTeX source\n\nI maintain a resume for both DevSecOps and Enterprise Cyber Security due to my extensive experience in both security domains\n\nMy resume is a polyglot PDF that self-contains its own git repo!\n\nTo retrieve the source code from the PDF, just run `git clone CJ_May_Resume.pdf resume_source/`"
                draft: false
                prerelease: false
