name: Generate Polyglot

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".deps"
      - "archive/**"
      - "Dockerfile"
      - "README.md"
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        container: ghcr.io/lawndoc/gitpdf:master
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Build Polyglot PDFs
              run: |
                make -f Makefile_DevSecOps
                make -f Makefile_CyberSec

            - name: Set release tag
              id: tag
              run: echo "TAG=$(date +'%Y-%m-%d')_$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
            
            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "release/CJ_May_Resume_DevSecOps.pdf,release/CJ_May_Resume_CyberSec.pdf"
                token: ${{ secrets.GITHUB_TOKEN }}
                tag: ${{ steps.tag.outputs.TAG }}
                name: "CJ May Resume"
                body: "*Automatically generated PDFs from LaTeX source*\n\nI maintain a resume for both DevSecOps and Enterprise Cyber Security to group relevant experience.\n\nMy resume is a polyglot PDF that self-contains its own git repo!\nTo retrieve the source code from the PDF, just run `git clone CJ_May_Resume.pdf source/`"
                draft: false
                prerelease: false
